# Generated by Django 4.2.7 on 2023-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=1)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
